language: node_js
dist: trusty
sudo: required
branches:
  only:
    - master
    - develop
node_js:
  - '8'
  - '10'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install: yarn --frozen-lockfile
script:
  - node --version
  - yarn --version
  - yarn lint
  - yarn test
cache:
  yarn: true
  directories:
    - node_modules
